apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: api-email-alert
  namespace: monitoring
  labels:
    app: api
spec:
  route:
    matchers:
      - name: alertname
        matchType: =~
        value: "Api.*"
    receiver: email-personal
    groupBy: [alertname, severity]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h

  receivers:
    - name: email-personal
      emailConfigs:
        - to: Hoangkimhung2004@gmail.com
          from: alertmanager-gitops@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: alertmanager-gitops@gmail.com
          authPassword:
            name: alertmanager-smtp
            key: password
          requireTLS: true
          sendResolved: true
