FROM python:3.12-slim
RUN pip install flask prometheus-flask-exporter
COPY app.py /app/app.py
WORKDIR /app
ENV FLASK_APP=app.py
ENV ERROR_RATE=0.8
ENV VERSION=v3-bad
EXPOSE 8080
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]
