apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "65.1.1"
    helm:
      values: |
        grafana:
          adminPassword: "accelerator123"
          persistence:
            enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelector: {}
            ruleNamespaceSelector: {}
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        alertmanager:
          config:
            global:
              smtp_smarthost: "smtp.gmail.com:587"
              smtp_from: "Hoangkimhung2004@gmail.com"
              smtp_auth_username: "Hoangkimhung2004@gmail.com"
              smtp_auth_password: "fxvr uimy qsyl eutn"
              smtp_require_tls: true
            route:
              group_by: [alertname, severity]
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 1h
              receiver: email-default
              routes:
                - matchers:
                    - alertname=~"Api.*"
                  receiver: email-api
            receivers:
              - name: email-default
                email_configs:
                  - to: Hoangkimhung2004@gmail.com
                    send_resolved: true
              - name: email-api
                email_configs:
                  - to: Hoangkimhung2004@gmail.com
                    send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
